name: 推送到本项目gh-page分支
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm i
    - run: git config --global user.name "actionbot"
    - run: git config --global user.email "actionbot@github.com"
    - run: GIT_USER=v GIT_PASS=${{ secrets.GITHUB_TOKEN }} npm run deploy